export const GET_PATIENTS = "GET_PATIENTS";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const ADD_ADDITIONAL_INFO_PATIENT = "ADD_ADDITIONAL_INFO_PATIENT";
export const ADD_USER_WITH_ADD_INFO = "ADD_USER_WITH_ADD_INFO";
export const SET_TRUE_VALID_EMAIL = "SET_TRUE_VALID_EMAIL";
export const SET_FALSE_VALID_EMAIL = "SET_FALSE_VALID_EMAIL";

export const BASIC_INFO_ADDED = "BASIC_INFO_ADDED";
export const ADDITIONAL_INFO_ADDED = "ADDITIONAL_INFO_ADDED";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const IMAGE_UPLOAD = "IMAGE_UPLOAD";

export const DONE_ADDING_NEW_PATIENT = "DONE_ADDING_NEW_PATIENT";
export const RETURN_TO_INITIAL_VALUES = "RETURN_TO_INITIAL_VALUES";

export const RIGTBAR_VISIBILITY = "RIGTBAR_VISIBILITY";

